Pull/issue35
SE701-T5/Frontend pull request #36
Opened 2022-03-16 21:14 UTC by christopher-alba

# Description

Add Ability to view uploaded images and delete them in New Post Page
- storing the image in a temporary local state using React hooks as a base64 string
- adding a new button to delete the image from the temporary local state that only shows when an image is uploaded
- a new image should add to the array of images in the local state
- using the react-responsive-carousel library to view the images

## Related Issue

Solves #35 

## Type of change

- [x] New feature (enhancement)

## How Has This Been Tested?

- [x] Manual testing

# Checklist:

- [x] Does a similar (open or closed) pull request not already exist?
- [x] Is the pull request _head_ repository a fork repository?
- [x] Is the pull request _compare_ branch a development branch?
- [ ] Is the code documented, particularly in hard-to-understand areas?
- [x] Does the code build without new warnings?
- [x] Has testing been performed that proves changes are effective and work?
- [ ] Has a self- and/or peer-review of the code been performed?
- [x] Have dependent changes been merged and published in downstream modules?
- [x] Is the person responsible for the repository assigned to the pull request?
- [x] Is the pull request linked to a project?
- [x] Is the pull request linked to a milestone?

For more information, refer to the [Contributing Guidelines](../blob/contribution-guidelines/.github/CONTRIBUTING.md) document.

2022-03-16 23:16 UTC, Xiaoqi510 requested changes
LGTM! But when i upload a img to the website, it shows me like that, i **cannot see the button POST.** i think maybe it's the problem of the npFormContainer padding-bottom, could u change that?
<img width="1440" alt="Screen Shot 2022-03-17 at 12 10 59 PM" src="https://user-images.githubusercontent.com/100509492/158706564-9c662cf2-7767-4763-9b5e-eda81a355cf3.png">
?

2022-03-17 00:02 UTC, Tvo465 reviewed
Looks good. I had a look at the preview and it seems everything is working and I didn't run into the problem like Xiaoqi did.

2022-03-17 00:13 UTC, Tvo465 approved these changes

2022-03-17 00:54 UTC, Xiaoqi510 approved these changes
It looks quite nice!!!

2022-03-17 00:56 UTC, merged