comment out console log
SE701-T5/Frontend pull request #94
Opened 2022-03-28 09:10 UTC by Sparye

# Description

## Related Issue

Solves #

## Type of change

- [ ] New feature (enhancement)
- [ ] Bug fix
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation

## How Has This Been Tested?

- [ ] Automated testing
- [ ] Manual testing

# Checklist:

- [ ] Does a similar (open or closed) pull request not already exist?
- [ ] Is the pull request _head_ repository a fork repository?
- [ ] Is the pull request _compare_ branch a development branch?
- [ ] Is the code documented, particularly in hard-to-understand areas?
- [ ] Does the code build without new warnings?
- [ ] Has testing been performed that proves changes are effective and work?
- [ ] Has a self- and/or peer-review of the code been performed?
- [ ] Have dependent changes been merged and published in downstream modules?
- [ ] Does all new and existing automated testing pass?
- [ ] Is the person responsible for the repository assigned to the pull request?
- [ ] Is the pull request linked to a project?
- [ ] Is the pull request linked to a milestone?

For more information, refer to the Contributing Guidelines and Code of Conduct links at the bottom of this page.

2022-03-29 07:32 UTC, GlockTian commented on src/pages/LoginRegister/RegisterPage.jsx
> +          console.log("failed to sign up");
as alert?

2022-03-29 07:32 UTC, GlockTian commented on src/pages/LoginRegister/ForgotPasswordPage.jsx
> +        email: 'admin@123',
probably should be email? I mean use the variable

2022-03-30 05:54 UTC, Sparye commented on src/pages/LoginRegister/RegisterPage.jsx
> +          console.log("failed to sign up");
I will change it to toast

2022-03-30 06:59 UTC, frasermcc9 commented
Please add a description

2022-03-30 07:06 UTC, frasermcc9 requested changes

2022-03-30 07:06 UTC, frasermcc9 commented on src/pages/LoginRegister/LoginPage.jsx
> +      localStorage.setItem("id", response.userID);
IMO this should be saved to localstorage as a single object (json stringified)

2022-03-30 07:06 UTC, frasermcc9 commented on src/pages/LoginRegister/LoginPage.jsx
> +      console.log(response);
```suggestion
```

2022-03-30 07:06 UTC, frasermcc9 commented on src/pages/LoginRegister/ForgotPasswordPage.jsx
> +              const email = document.getElementsByClassName('userEmail').value
Avoid imperative code like this.

Either useRef to get the element, or store the the value in state.

2022-03-30 07:06 UTC, frasermcc9 commented on src/pages/LoginRegister/LoginPage.jsx
> +    };
```suggestion
  const LoginFormDetail = async ({email, password: plaintextPassword}) => {
    const loginDetails = {
      data: {
        email,
        plaintextPassword,
      },
    };
```

Check this works first :P

2022-04-02 04:37 UTC, frasermcc9 submitted a review, later dismissed

2022-04-02 05:22 UTC, frasermcc9 requested changes
Can you make the register page go back to the login page if the register was successful?

2022-04-02 05:35 UTC, frasermcc9 approved these changes

2022-04-02 05:35 UTC, merged